### ISSUE TITLE
Use DP library in make project

### ISSUE THREAD

**Issue by ReichertL** [google/differential-privacy#121]
Hello,
I am sorry for bothering you with this question but I have been struggling for the past days and have not found a solution yet.

I want to use this differential privacy C library in a larger project which relies on `make`. 

The first idea was to create a .so or .a file which are mostly self containing. But apparently this is not possible as all the important code is contained inside `.h` files. Those do not produce .o files, so from my understanding no `.so` or `.a` files can be produced.
Simply copying all files from the library to the new make projects and including them does not work due to the dependencies, e.g. abseil and protobuf.

Does anyone have a suggestion on how this could (or *should*) be done? I do not want to switch my whole project to Bazel just because a single dependency relies on it.

Edit: Turns out it can be included with sources just like any other C++ third party library. I really got myself confused with trying to create an .so file, which is not possible.

**Comment by dibakch** [comment]
I believe you can use the linked files and the header files to use them in a Makefile.  You might also be able to automate this step and only require Bazel (or Bazelisk) for building the DP Lib.

You can find the `*.pb.h` files in the `cc/bazel-bin/external/com_google_differential_privacy/proto` folder. (They are external to the `./cc/` workspace as they are defined in the root workspace so that they are accessible also for other implementations in other languages).  You need to run `cd cc; bazliesk build ...` to generate the files.

Hope this helps :)

**Comment by ReichertL** [comment]
Thanks for the help.
I found the `*.pb.h` files. But it seems like my approach will be very unstable and only work for a single specific combination of library versions. I therefore decided to instead use bazel in parts of my main project, while still relying on the original make file when possible. 

As far as I understand it now the differential privacy library is more targeted for Googles internal use. Therefore it is basically assumed that bazel is used during all steps. However, this makes it very difficult for others to integrate the library into existing projects which are not bazel based.
