### ISSUE TITLE
Updated Maven artifacts?

### ISSUE THREAD

**Issue by jameskyle** [google/differential-privacy#128]
I've noticed the artifacts in the maven repositories are over a year out of date. 

Are there plans to make maven publishing part of the standard release cycle? 

It would really cut down on the friction to integrate the dp libraries into a project.

Cheers!

**Comment by miracvbasaran** [comment]
Hey James,

Thanks for raising this!

Publishing to Maven is indeed a part of our standard release cycle. It's just that we've only had [patch releases](https://github.com/google/differential-privacy/releases) for specific bugs since v1.1.0 (the latest Maven release), and none of those patch releases were related to Java code.

We plan to release v2.0.0 hopefully soon, and we will publish it to Maven when we do.

I hope that answers your question.

**Comment by xerial** [comment]
@miracvbasaran Good to know that. I'm looking forward to the new Maven release

**Comment by xerial** [comment]
@miracvbasaran Thanks for releasing 2.0.0, but I still haven't seen any Maven artifact for 2.0.0 at:
https://repo1.maven.org/maven2/com/google/privacy/differentialprivacy/

I guess we need to wait for a while.

**Comment by miracvbasaran** [comment]
Hey Taro,

We have already started the process for publishing the Maven artifact but unfortunately the process can take a couple of days. It should be available soon!

**Comment by dibakch** [comment]
You can find the 2.0.0 artifacts at https://search.maven.org/artifact/com.google.privacy.differentialprivacy/differentialprivacy

**Comment by xerial** [comment]
Awesome. Thanks!
