### ISSUE TITLE
[Question] Generate differential private release of a dataset?

### ISSUE THREAD

**Issue by sasvaritoni** [google/differential-privacy#61]
Hi,

I can see the examples for different statistics queries.
I am wondering if the Google DP library could be used to generate a differential private release of a dataset. I mean to transform the original dataset to an "anonymized" one.
Is this planned for the future maybe?

Thanks,
Toni

**Comment by dasmdasm** [comment]
We have no plans to build anything like that. Generating an anonymized version of a dataset is a really hard problem, and building a general-purpose solution is even harder. From a utility perspective it's almost always going to be better to do a computation in a differentially private manner rather than making a general-purpose differentially private dataset and then doing your computation on that dataset.
